// Generated by Wrangler by running `wrangler types`

interface Env {
	WEATHER_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").WeatherDurableObject>;
	TIDE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").TideDurableObject>;
}
declare module "*.graphql" {
	const value: string;
	export default value;
}